version: '3'

services:
    mariadb:
        image: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        networks:
            - monreseau
        # volumes:
        #     - ../data/mariadb:/var/lib/mysql
        env_file: .env
        restart: always

    wordpress:
        depends_on:
            - mariadb
        image: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        networks:
            - monreseau
        volumes:
            - ../data/wordpress:/var/www/html
        tty: true
        restart: always

    nginx:
        depends_on:
            - wordpress
        env_file: .env
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx
        tty: true
        ports:
            - 443:443
        networks:
            - monreseau
        volumes:
            - ../data/wordpress:/var/www/html/
        restart: always

networks:
    monreseau:
        driver: bridge
