version: '3'

services:
    mariadb:
        image: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        networks:
            - monreseau
        # volumes:
        #     - ../data/mariadb:/var/lib/mysql
        env_file: .env
        restart: always

    wordpress:
        depends_on:
            - mariadb
            - redis
        image: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        networks:
            - monreseau
        volumes:
            - ../data/wordpress:/var/www/html
        tty: true
        restart: always

    nginx:
        depends_on:
            - wordpress
        env_file: .env
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx
        tty: true
        ports:
            - 443:443
        networks:
            - monreseau
        volumes:
            - ../data/wordpress:/var/www/html/
        restart: always

    adminer:
        image: adminer
        depends_on:
            - mariadb
        build:
            context: ./requirements/adminer
            dockerfile: Dockerfile
        networks:
            - monreseau
        environment:
            ADMINER_DEFAULT_DB_DRIVER: mysql
            ADMINER_DEFAULT_DB_HOST: mariadb
            ADMINER_DEFAULT_DB_NAME: adminer
        volumes:
            - ../data/wordpress:/var/www/html/
        # restart: always

    redis:
        image: redis
        build:
            context: ./requirements/redis
            dockerfile: Dockerfile
        tty: true
        networks:
			- monreseau

	website:
		image: website
		build: 
			context: ./requirements/website
			dockerfile: Dockerfile
		networks: 
			- monreseau
		volumes:
			- ../data/wordpress:/var/www/html/

networks:
    monreseau:
        driver: bridge
