version: '3'

services:
    mariadb:
        image: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        networks:
            - monreseau
        env_file: .env
        restart: always

    wordpress:
        depends_on:
            - mariadb
            - redis
        image: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        networks:
            - monreseau
        volumes:
            - wordpress:/var/www/html
        tty: true
        restart: always

    nginx:
        depends_on:
            - wordpress
        env_file: .env
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx
        tty: true
        ports:
            - 443:443
        networks:
            - monreseau
        volumes:
            - wordpress:/var/www/html/
        restart: always

    adminer:
        image: adminer
        depends_on:
            - mariadb
        build:
            context: ./requirements/adminer
            dockerfile: Dockerfile
        networks:
            - monreseau
        environment:
            ADMINER_DEFAULT_DB_DRIVER: mysql
            ADMINER_DEFAULT_DB_HOST: mariadb
            ADMINER_DEFAULT_DB_NAME: adminer
        volumes:
            - wordpress:/var/www/html/

    redis:
        image: redis
        build:
            context: ./requirements/redis
            dockerfile: Dockerfile
        tty: true
        networks:
            - monreseau

    website:
        image: website
        build:
            context: ./requirements/website
            dockerfile: Dockerfile
        networks:
            - monreseau
        volumes:
            - wordpress:/var/www/html/


volumes:
    wordpress:
        driver_opts:
            type: none
            device: /home/sohechai/data/wordpress
            o: bind
    mariadb:
        driver_opts:
            type: none
            device: /home/sohechai/data/mariadb
            o: bind
networks:
    monreseau:
        driver: bridge
